### ISSUE TITLE
Add and/or use additional `expect equals` helpers to the fixture

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#2402]
Helpers like these with messages about what they expected and what they actually got makes debugging failures easier.

Currently they can be opaque. For example, in the error scope tests:

```
webgpu_cts_integration_test.py(341): AssertionError:   - EXPECTATION FAILED
    Error
        at ErrorScopeTests.expect (http://127.0.0.1:36873/third_party/webgpu-cts/src/common/framework/fixture.js:242:40)
        at RunCaseSpecific.fn (http://127.0.0.1:36873/third_party/webgpu-cts/src/webgpu/api/validation/error_scope.spec.js:114:11)
```

This is because the expectations are checking a boolean, like below:

```typescript
t.expect(t.isInstanceOfError(errorType, error));
```

 ```typescript
 const errors = await Promise.all(promises);
    t.expect(errors.every(e => e === null));
```

**Comment by kainino0x** [comment]
This would be good. If we can write this in a way that works well for both `assert` and `expect`, I think that would be nice. We could have a small library of checks that return a specially-typed, pretty-printable object, and have `assert`/`expect` detect that object type and handle it appropriately for the check and print.

History: very early on I had hoped to run a code transform that would break down assert/expect expressions and pretty-print their components ([power-assert)](https://github.com/power-assert-js/power-assert)) but this didn't make sense once we started talking about having the JS output be debuggable/usable on its own.
