### ISSUE TITLE
Fix skip vs pass priority

### ISSUE THREAD

**Issue by greggman** [gpuweb/cts#3021]
AFAICT, the code right now marks a case as `skip` if any subcases skip, even if some pass and none fail. In other words, imagine you have 3 subcases

   subcase 1: pass
   subcase 2: skip
   subcase 3: pass

The "case" will be reported as "skip" when it seems like it should be reported as "pass". This seems to be because, for the entire case, only the highest value `LogSeverity` is kept and Skip (1) is greater than Pass (0). 

I thought a simple fix would be to Skip = 0 and Pass = 1 but when I tried it lots of unittests broke. I looked for a while but got lost in the weeds.

Should this be fixed or is this working as intended, that a case with passing subcases and 1 or more skipped subcases is reported as "skip" instead of "pass"?

**Comment by greggman** [comment]
@kainino0x

**Comment by greggman** [comment]
I'm also running into an error here

compatibility=1&q=webgpu:api,validation,encoding,cmds,copyTextureToTexture:texture_format_compatibility:*

Where I get

```
EXCEPTION: internal error: case is "skip" but has non-skipped subcases
    at TestCaseRecorder.finish (http://localhost:8080/out/common/internal/logging/test_case_recorder.js:55:18)
    at RunCaseSpecific.run (http://localhost:8080/out/common/internal/test_group.js:698:11)
```

Not sure it's related but there are no failures, lots of skips and lots of "OK" and at the end the error above

**Comment by greggman** [comment]
https://github.com/gpuweb/cts/pull/3036

**Comment by kainino0x** [comment]
I've got a lot in my email backlog, but on quick inspection yes, it seems like this logic is questionable. It was added before subcases existed. But I don't know the right way to fix it.

Maybe it's just to rename Skip to PassWithSkips...? And fix or remove that internal error you ran into (I just added that recently).
