### ISSUE TITLE
image_copy CTS tests recently started failing for depth formats 

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/cts#3199]
I noticed the following tests recently started failing:

```
webgpu:api,operation,command_buffer,image_copy:rowsPerImage_and_bytesPerRow_depth_stencil:format="depth16unorm";copyMethod="CopyT2B";aspect="depth-only"
webgpu:api,operation,command_buffer,image_copy:rowsPerImage_and_bytesPerRow_depth_stencil:format="depth32float";copyMethod="CopyT2B";aspect="depth-only"
webgpu:api,operation,command_buffer,image_copy:rowsPerImage_and_bytesPerRow_depth_stencil:format="depth32float-stencil8";copyMethod="CopyT2B";aspect="depth-only"
```

on Apple Silicon Macs on Chrome Canary (121.0.6158.0) and Chrome (119.0.6045.159) and I also see the same failure on WebKit with `-DENABLEWEBGPU_BY_DEFAULT=1`

It appears to have regressed with `90b8a3e9079f905eb34b9def1f542df32d8e9009` or `36319467f5681497546244d179aebee6ba25128e`, do you happen to know @greggman ? Are the new expectations correct?

The failures look like:
```
EXPECTATION FAILED: subcase: bytesPerRowPadding=0;rowsPerImagePadding=0;copyWidthInBlocks=3;copyHeightInBlocks=4;copyDepth=5;mipLevel=0
Array had unexpected contents at indices 1024 through 4874.
 Starting at index 1023:
   actual == 0x: 00 00 00 80 3f cd cc 4c 3d cd cc cc 3d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ...
   failed ->        xx xx xx    xx xx xx xx xx xx xx xx                                                                   ...
 expected ==     00 9a 99 19 3f 66 66 26 3f 33 33 33 3f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ...
Error
    at ImageCopyTest.eventualAsyncExpectation (https://gpuweb.github.io/cts/out/common/framework/fixture.js:202:24)
    at ImageCopyTest.expectGPUBufferValuesPassCheck (https://gpuweb.github.io/cts/out/webgpu/gpu_test.js:473:10)
    at ImageCopyTest.expectGPUBufferValuesEqual (https://gpuweb.github.io/cts/out/webgpu/gpu_test.js:489:10)
    at ImageCopyTest.DoCopyTextureToBufferWithDepthAspectTest (https://gpuweb.github.io/cts/out/webgpu/api/operation/command_buffer/image_copy.spec.js:1354:10)
    at RunCaseSpecific.fn (https://gpuweb.github.io/cts/out/webgpu/api/operation/command_buffer/image_copy.spec.js:2019:9)
```

**Comment by greggman** [comment]
Sorry, my bad.

**Comment by mwyrzykowski** [comment]
No problem, thanks for fixing it so quickly!
