### ISSUE TITLE
`popErrorScope failed; did beginTestScope get missed?`

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/cts#3268]
While trying to debug a device lost issue with `webgpu:shader,execution,expression,call,user,ptr_params:mixed_ptr_parameters:*`, I get the following exception:

```
  - EXCEPTION: popErrorScope failed; did beginTestScope get missed?
        at assert (C:\src\dawn\third_party\webgpu-cts\out-node\common\util\util.js:30:15)
        at DeviceHolder.attemptEndTestScope (C:\src\dawn\third_party\webgpu-cts\out-node\webgpu\util\device_pool.js:285:34)
        at async DevicePool.release (C:\src\dawn\third_party\webgpu-cts\out-node\webgpu\util\device_pool.js:51:13)
        at async Promise.all (index 0)
        at async GPUTestSubcaseBatchState.finalize (C:\src\dawn\third_party\webgpu-cts\out-node\webgpu\gpu_test.js:50:9)
        at async RunCaseSpecific.run (C:\src\dawn\third_party\webgpu-cts\out-node\common\internal\test_group.js:433:17)
        at async C:\src\dawn\third_party\webgpu-cts\out-node\common\runtime\cmdline.js:173:9
```

It's entirely possible that the test should be doing something different, but it's not obvious to me what I should change, or if this is my bug.

**Comment by ben-clayton** [comment]
It was an issue with dawn/node. Internal errors were not hooked up, and instead threw an exception.
