### ISSUE TITLE
`npm test` is failing with `Generated test variant would produce too-long -actual.txt filename`

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/cts#3676]
```
Running "run:write-out-wpt-cts-html-chunked2sec" (run) task
Error: Generated test variant would produce too-long -actual.txt filename. Possible solutions:
- Reduce the length of the parts of the test query
- Reduce the parameterization of the test
- Make the test function faster and regenerate the listing_meta entry
- Reduce the specificity of test expectations (if you're using them)
webgpu:shader,validation,expression,call,builtin,textureLoad:texture_type,non_storage:testTextureType="texture_storage_1d%3Crgba8unorm,%20read%3E";textureType="texture_multisampled_2d";*
    at assert (/home/ben/src/dawn/third_party/webgpu-cts/src/common/util/util.ts:37:11)
    at /home/ben/src/dawn/third_party/webgpu-cts/src/common/tools/gen_wpt_cts_html.ts:222:15
```

**Comment by greggman** [comment]
On it.

But, was some build step removed? `npm test` used to complain if a test was missing from `listing_meta.json` so it wouldn't have committed before. @kainino0x ?

**Comment by kainino0x** [comment]
> But, was some build step removed? `npm test` used to complain if a test was missing from `listing_meta.json` so it wouldn't have committed before. @kainino0x ?

#3548

**Comment by kainino0x** [comment]
> This is updated automatically with `run-cts`.

Beware run-cts producing a number that's way too big: https://crbug.com/dawn/2468

**Comment by ben-clayton** [comment]
Fixed.
