### ISSUE TITLE
Deno can't run the test suite

### ISSUE THREAD

**Issue by turbocrime** [gpuweb/cts#4123]
trying to use this test suite to validate some changes i'm making to gfx-rs/wgpu which uses deno to run the suite. that repo references quite an old cts revision. using a more modern version of the suite, with tests for the features i'm interested in, breaks their `cts_runner` tool.

but, the failure is the same between their `cts_runner`, and also manual execution with the latest stable deno release v2.1.4 on tip of gpuweb/cts@main.

## problem

it seems like deno can no longer run this test suite.

### using `cts_runner`

using wgpu's `cts_runner` with an updated cts revision results in this failure:

```
error: Relative import path "fs" not prefixed with / or ./ or ../ from "file:///Users/yet/Developer/github.com/gfx-rs/wgpu/cts/out/common/runtime/cmdline.js"
```

### using `node:fs` import

it seems like deno is mistaking the node `fs` module for a local module path. looking at deno documentation, it seems that [importing a node module now requires a node-protocol prefix](https://docs.deno.com/runtime/fundamentals/node/#using-node's-built-in-modules). updating the import to `node:fs` doesn't actually fix anything

```
error: Provided module specifier "node:fs" is not a file URL.
```

this is strange, because deno is documented to support this module.

### without `cts_runner`

i wonder if it's something to do with wgpu's specific runner setup, so i simply try calling the `run_deno` script,

#### with `./tools/run_deno` directly

 seems to match the cts_runner failure

```
⚠️  The `--unstable` flag has been removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
error: Relative import path "fs" not prefixed with / or ./ or ../
  hint: If you want to use a built-in Node module, add a "node:" prefix (ex. "node:fs").
    at file:///Users/yet/Developer/github.com/gfx-rs/wgpu/cts/out/common/runtime/cmdline.js:3:24
```

#### with `deno ./tools/run_deno`

essentially omits the cli flags in the hashbang

```
error: Uncaught (in promise) ReferenceError: require is not defined
  const { existsSync } = require('fs');
                         ^
    at node (file:///Users/yet/Developer/github.com/gfx-rs/wgpu/cts/out/common/runtime/helper/sys.js:5:26)
    at file:///Users/yet/Developer/github.com/gfx-rs/wgpu/cts/out/common/runtime/helper/sys.js:44:57

    info: Deno supports CommonJS modules in .cjs files, or when the closest
          package.json has a "type": "commonjs" option.
    hint: Rewrite this module to ESM,
          or change the file extension to .cjs,
          or add package.json next to the file with "type": "commonjs" option,
          or pass --unstable-detect-cjs flag to detect CommonJS when loading.
    docs: https://docs.deno.com/go/commonjs
```

according to documentation, deno should support use of node's `fs` module, and it's unclear why this doesn't work.

i suspect it might have something to do with the command-line flags on the `tools/run_deno` script, which are apparently out of date (issue soon)

#### workaround already present

at this point i noticed that a workaround seems to already exist within `cmdline.ts`.

all node modules are accessed via `helper/sys.ts`

https://github.com/gpuweb/cts/blob/main/src/common/runtime/helper/sys.ts

## suspected problem

other node utilities are accessed via the `helper/sys` module, and the section of code directly using `fs.readFile` was added later. this seems inconsistent.

https://github.com/gpuweb/cts/commit/ea0cfebc612f28cab2a7a0bfbb31f6622864c4d6#diff-fe71a942bd25eff623744571b92fff7fe320776150c5accb817c01d442dd110e

correcting this (pr soon) does allow the test suite to execute with deno.

**Comment by kainino0x** [comment]
Thanks for the report and investigation! We (the core group of WebGPU people, who work on the browsers) are not working on maintaining Deno support at all, but it's great to have it working. Will be glad to take a PR.

**Comment by andyleiserson** [comment]
I believe this was fixed by the linked PR.
